Сделали шифроваие сообщений и ссылок + работа с privatty
kib-sources/stego-mp4-link pull request #11
Opened 2023-02-27 10:32 UTC by yourProgrammist

Поменяли сервис записок и ссылок на другие, так как у них есть API

2023-02-27 10:36 UTC, nurovAm approved these changes

2023-02-27 19:26 UTC, PavelMSTU requested changes
**Отписал замечания.**

Глобально:
1. Есть много когнитивной нагрузки. Есть один пример в комментах -- посмотрите. Нужно везде её убрать
2. нужен файл `core\errors.py`
3. тест вынести из `core` в папку `tests\<что_тестируем>.py`. Так же тесты так не пишут. См. хотя бы так https://docs.python.org/3/library/unittest.html
4. не вижу обнавлений в `requirements.txt`. Какие версии каких библиотек должны быть установлены в python. Сделайте `venv`, установите всё, потом `(venv)$ pip freeze > requirements.txt`

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +        keys = PBKDF2(password, self.salt, 64, count=1000000, hmac_hash_module=SHA512)
1. Убра ть 64 как magic число.
2. Разделить вызов PBKDF2 на шаги "лесенкой" для лучшего чтения (см. пример ниже)
3. `keys` -- это множество от `key` (т.е. это кортеж или список ключей). У вас это конкатенация. Лучше поменять название на `keys_bytes`

Написать в глобальных переменных 
```python
KEY_LENGTH = 32
```

То есть
```python
keys_bytes = PBKDF2(
    password, 
    clf.salt, 
    2 * KEY_LENGTH, 
    count=cls._count, 
    hmac_hash_module=SHA512,
)

key1 = keys_bytes[:32]
key2 = keys_bytes[32:]

```

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +    def decryptmassage(self, password: str, base64_message: bytes):
Здесь, а так же везде где есть `@classmethod` не нужно назвать первую переменну `self`, нужно `cls`:

```python
 @classmethod
 def decryptmassage(cls, password: str, base64_message: bytes) -> bytes:
    ...
```

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +        result = s.encode('latin1').decode('unicode_escape').encode('latin1')
Не `latin1`, а `ascii`.

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +        result = s.encode('latin1').decode('unicode_escape').encode('latin1')
плюс вынести кодировку в глобальные настройки

```python
STEGO_ENCODING = 'ascii'
...

result = s.encode(STEGO_ENCODING).decode('unicode_escape').encode(STEGO_ENCODING)
```

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +        for each_split in split_message:
А может шифром Цезаря?.. 

Сделайте нормальное шифрование. Возьмите AES, например

2023-02-27 19:26 UTC, PavelMSTU commented on core/cipher.py
> +        # дешифруем
расшифровываем.

**decrypt -> расшифровать
break -> дешифровать**

Да, глупо получилось, но это было до нашего рождения...

2023-02-27 19:26 UTC, PavelMSTU commented on core/clck.py
> +        headers = {'x-goo-api-token': 'wiA1hUZnkvk7AvotYafUjjpXOsoiIpkj8kGLL8E7UHaLljVnp8nku47wSRvS'}  # API-токен
**Грубейшая ошибка.** 
Подробнее на звонке.

1. Все API токены и другие секреты засовываем в `.env` файл, предварительно добавив его в `.gitignore`.
2. Создаем `.env_example` где перечисляем примеры токенов, заблюрив часть звёздочками.
3. Настраиваем проброску `.env` при старте.

2023-02-27 19:26 UTC, PavelMSTU commented on core/clck.py
> +            "group_id": 2
Магические числа. Поясните комментариями.

2023-02-27 19:26 UTC, PavelMSTU commented on core/privatty.py
> +        driver.find_element(By.XPATH, "/html/body/div[1]/main/div/div/div[3]/a[1]").click()
Когнитивная нагрузка... 

Много в одной строке.

Может так?
```python
driver.find_element(
   By.XPATH, 
   "/html/body/div[1]/main/div/div/div[3]/a[1]"
).click()
```

2023-02-27 19:26 UTC, PavelMSTU commented on core/privatty.py
> +        driver.find_element(By.XPATH, "/html/body/div[1]/main/div/div/div[3]/a[1]").click()
Вообще много где когнитивная нагрузка... Посмотрите ещё раз свежим взглядом **на весь код** и разбейте.

В качестве лайфхака: покажите код другой команде. Пусть скажут насколько это читабельно.

2023-02-27 19:26 UTC, PavelMSTU commented on core/test.py
> +class PasswordError(Exception):
1. Все ошибки вынесите в отдельный файл `core\errors.py`. 
2. К каждой ошибке дайте описание
3. Создайте базовую ошибку

```python
class BaseStegoProjectErrot(Exception):
    """
     Базовая ошибка проектов stego-***
    """
    pass

class PasswordError(BaseStegoProjectErrot):
    """
    ...
    """

...
```

2023-02-27 19:26 UTC, PavelMSTU commented on core/test.py
> +if __name__ == "__main__":
Слишком большой код под `if __name__ == "__main__":` 

Вынесите в отдельную функцию:

```python
if __name__ == "__main__":
    args = parser.parse_args()
    main(args)
    exit()
```

2023-02-27 19:26 UTC, PavelMSTU commented on core/test.py
> +    parser.add_argument(
Все ` parser.add_argument(...)` сделайте глобальными.

```python
if __name__ == "__main__":
     ...
else:
    raise Exception(f"Файл {__file__} должен быть запускаемым")

2023-02-27 19:26 UTC, PavelMSTU commented on core/test.py
> +'''
Примеры описать в `__doc__` файла.

2023-03-06 22:42 UTC, yourProgrammist commented
Не смогли изменить кодировку latin1 на ASCII, так как не видим другого пути избавить от экранирования _бэк-слешей_

![image](https://user-images.githubusercontent.com/59966999/223268295-9c7786c8-6aae-45aa-8626-84e30f449015.png)

2023-03-08 09:17 UTC, PavelMSTU requested changes
Гораздо лучше. Есть ещё замечания небольшие.

2023-03-08 09:17 UTC, PavelMSTU commented on core/errors.py
> +class WrongPassword(BaseStegoProjectError):
Сделайте отдельную ошибку `PasswoedError` и уже от неё наследуйте все ваши ошибки.

**На будущее:** в принипе не нужна такая детализация. Достаточно было только одного `PasswoedError`, а детализировать уже в сообщении:
```python
raise PasswoedError("Пароль нужно вводить латиницей")
...
raise PasswoedError("Длина пароля слишком мала.")
...
```

2023-03-08 09:17 UTC, PavelMSTU commented on core/errors.py
> +    Ошибка длины пароля (должна быть больше 6)+
Минимальная длина пароля никогда не была 6 символов. Раньше 8 символов, сейчас считается от 9.
Это с учётом цифр, ЗАГЛАВНЫХ и специцальных символов (#, $ и т.д)

2023-03-08 09:17 UTC, PavelMSTU commented on core/errors.py
> +    Ошибка нахождения символов из кириллицы в пароле+
Не обязательно кириллицы, любого не acsii символа. 

См. греческий, армянский, тамильский и т.д. алфавиты.

2023-03-08 09:17 UTC, PavelMSTU commented on core/errors.py
> +    Ошибка отсутствия пароля+
Речь. 
"Пароль отсутствует."

2023-03-08 09:17 UTC, PavelMSTU commented on core/errors.py
> +class MessageHasRead(BaseStegoProjectError):
`MessageHasAlreadyRead`

2023-03-08 09:17 UTC, PavelMSTU commented on core/main.py
> +        if len(args.password) < 7:
< 9

Саму 9 занесите в settings.py

2023-03-08 09:17 UTC, PavelMSTU commented on core/main.py
> +        if (set('абвгдеёжзийклмнопрстуфхцчшщъыьэюя\\').isdisjoint(args.massage.lower())) == 0:
Наоборот, проверяем что только латинсккие

```
from string import ascii_letters

def check(word):
    return all(map(lambda c: c in ascii_letters, nickname))
```

2023-03-08 09:17 UTC, PavelMSTU commented on tests/write_read_privatty.py
> +sys.path.insert(1, os.path.join(sys.path[0], '../core'))
Не надо так делать. 

Просто во всех файлах из `core` делайте импорт из самого проекта.

```
from core.cipher import ...
```

2023-03-08 09:17 UTC, PavelMSTU commented on core/main.py
> +"""
Почему этот файл в core ?

2023-03-08 09:17 UTC, PavelMSTU commented on core/main.py
> +"""
В корне проекта может перенести?

2023-03-08 12:03 UTC, yourProgrammist commented on core/errors.py
> +class MessageHasRead(BaseStegoProjectError):
https://github.com/kib-sources/stego-mp4-link/pull/11/commits/755b6efe9300eaa0d019e335d98aaa471ff556ec

2023-03-08 12:03 UTC, yourProgrammist commented on core/errors.py
> +    Ошибка нахождения символов из кириллицы в пароле+
https://github.com/kib-sources/stego-mp4-link/pull/11/commits/755b6efe9300eaa0d019e335d98aaa471ff556ec

2023-03-08 12:03 UTC, yourProgrammist commented on core/errors.py
> +    Ошибка длины пароля (должна быть больше 6)+
https://github.com/kib-sources/stego-mp4-link/pull/11/commits/755b6efe9300eaa0d019e335d98aaa471ff556ec

2023-03-11 09:06 UTC, PavelMSTU approved these changes
Файл `..gitignore` пустой...
Заполните отсюда: https://github.com/kib-sources/stego-gif-layers/blob/master/.gitignore

Давайте уже в других задачах

2023-03-11 09:06 UTC, merged