Issue010
kib-sources/stego-mp4-link pull request #14
Opened 2023-03-23 21:47 UTC by nurovam

Сделали блок записи и соединили с предущими блоками.

2023-03-23 23:21 UTC, yourProgrammist commented
Examples bash:
~$python3 stego.py -a write -p password123 -m Massage -i poc/sample3.m4a -o poc/stego.m4a
~$python3 stego.py -a read -p password123 -o poc/stego.m4a

2023-03-23 23:24 UTC, yourProgrammist approved these changes

2023-03-26 07:56 UTC, PavelMSTU requested changes
Небольшие замечания внёс.

2023-03-26 07:56 UTC, PavelMSTU commented on core/errors.py
> +class WriteError(BaseStegoProjectError):
А `ReadError` есть? 

Судя по ошибкам наследования, я бы поменял на `FileContainerError`. 

И наверное уже не разбивал бы на `FormatError`

2023-03-26 07:56 UTC, PavelMSTU commented on core/errors.py
> +class NoM4a(WriteError):
FormatError достаточно.

2023-03-26 07:56 UTC, PavelMSTU commented on core/errors.py
> +class NoFile(WriteError):
Стандартная ошибка `IOError` есть.

2023-03-26 07:56 UTC, PavelMSTU commented on core/main.py
>              bytes(en_massage, encoding='utf-8')))[2:-1]
Божечки... Что здесь происходит? 
Разбить на 2-3 линии.

Или вынести в функцию.

2023-03-26 07:56 UTC, PavelMSTU commented on core/privatty.py
> +    url_privatty = "https://safenote.co/"
Может `url_privatty` вынести в глобальную переменную? 

Так же разумно сделать базовый класс `BasePrivatty`:
```python
class PrivattySafenote(BasePrivatty):
    ...
```

Базовый класс будет содержать в себе неопределённые функции, например:
```python
 def write_message(cls, message: str) -> str:
    return NotImplemented
```

Цель базового класса -- предоставить будущим разработчикам написать свои Privatty классы.

2023-03-26 07:56 UTC, PavelMSTU commented on tests/test_work_with_m4a.py
> +~tests/test_work_with_m4a.py
Как использовать это из консоли пару примеров в `__doc__` сделайте.

```python
"""
Тест на запись чтение файлов m4a
Create at 27.02.2023 12:43:59
~tests/test_work_with_m4a.py

Это делает то-то
>> python -m tests.test_work_woth_m4a  <КЛЮЧИ>

А Это делает сё-то
>> python -m tests.test_work_woth_m4a  <ДРУГИЕ КЛЮЧИ>

А Это делает сё-то-cё-то
>> python -m tests.test_work_woth_m4a  <И ЕЩЁ ДРУГИЕ КЛЮЧИ>


""" 

__authors__ = [
    'yourProgrammist',
    'nurovAm'
]
```

2023-03-26 07:56 UTC, PavelMSTU commented on write_read_m4a/write.py
> +def nib(link: list[chr]) -> list[str]:
Можно функции дать более осмысленное название? 
Ини написать к ней `__doc__` ?

2023-03-26 07:56 UTC, PavelMSTU commented on write_read_m4a/write.py
> +        elif i == 48 and len(nibbles) > 4:
magic индексы. Здесь и далее. 
Дать пояснения.

2023-03-28 09:13 UTC, yourProgrammist commented on tests/test_work_with_m4a.py
> +~tests/test_work_with_m4a.py
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 09:13 UTC, yourProgrammist commented on core/privatty.py
> +    url_privatty = "https://safenote.co/"
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 09:13 UTC, yourProgrammist commented on core/main.py
>              bytes(en_massage, encoding='utf-8')))[2:-1]
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 09:14 UTC, yourProgrammist commented on core/errors.py
> +class NoFile(WriteError):
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 09:14 UTC, yourProgrammist commented on core/errors.py
> +class NoM4a(WriteError):
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 09:14 UTC, yourProgrammist commented on core/errors.py
> +class WriteError(BaseStegoProjectError):
https://github.com/kib-sources/stego-mp4-link/pull/14/commits/bebe42f0dca356498d3074c3ec578c66abca1367

2023-03-28 10:38 UTC, PavelMSTU approved these changes
Вроде ок. :)

2023-03-28 10:54 UTC, yourProgrammist commented
Перетащил _write_read_m4a_ в **core**

2023-03-28 12:19 UTC, merged