Создал базовый класс, добавил флаги.
kib-sources/stego-mp4-link pull request #19
Opened 2023-05-14 10:02 UTC by yourProgrammist

2023-05-14 15:08 UTC, nurovAm approved these changes

2023-05-15 10:53 UTC, PavelMSTU requested changes

2023-05-15 10:53 UTC, PavelMSTU commented on core/sdarn/base.py
> +    _base_url = None
добавить:
```python
name = None
```

2023-05-15 10:53 UTC, PavelMSTU commented on core/sdarn/onetimesecret.py
> +        assert link.startswith("https://goo.su/")
Разделение между `raw_write` и `write` была в следующая:
1. `wrire` искомое сообщение шифрует
2. записывает в base64 
3. вызывает  `raw_write` 

Таким образом `write` и `read` разумно реализовать в базовом классе, а в наследниках только `raw_write` и `raw_read` сделать. 

По поводу ссылок, в частности "https://goo.su/". 

Это уже следующий уровень и его НЕ НАДО вписывать в Sdarn

Кстати, для него разумно тоже сделать базовый класс и наследник для "https://goo.su/"

2023-05-15 10:53 UTC, PavelMSTU commented on core/sdarn/privatty.py
> +        assert link.startswith("https://goo.su/")
Аналогичные замечания, как для OneTimeSecretSdarn

2023-05-15 10:53 UTC, PavelMSTU commented on stego.py
> +""")
Как это миило! :)) 

Сделать issue для других stego проектов по банеру. Сослаться на этот.

2023-05-15 10:53 UTC, PavelMSTU commented on tests/test_work_with_m4a_onetimesecret.py
> +"""
Пробельные строки добавьте... Неудобно читать же...

2023-05-15 10:53 UTC, PavelMSTU commented on tests/test_work_with_m4a_onetimesecret.py
> +    unittest.main()
Данный модуль не импортируется же?

Тогда:
```python
if __name__ == "__main__":
    unittest.main()
else:
    raise Exception(f"Модуль {__name__} не импортируется!")

```

2023-05-15 15:52 UTC, yourProgrammist commented on tests/test_work_with_m4a_onetimesecret.py
> +"""
[4cd27ce](https://github.com/kib-sources/stego-mp4-link/pull/19/commits/4cd27cec63f2b189caf8f631d9a9f74a3aafba17)

2023-05-15 15:53 UTC, yourProgrammist commented on core/sdarn/onetimesecret.py
> +        assert link.startswith("https://goo.su/")
[4cd27ce](https://github.com/kib-sources/stego-mp4-link/pull/19/commits/4cd27cec63f2b189caf8f631d9a9f74a3aafba17)

2023-05-15 15:53 UTC, yourProgrammist commented on core/sdarn/base.py
> +    _base_url = None
[4cd27ce](https://github.com/kib-sources/stego-mp4-link/pull/19/commits/4cd27cec63f2b189caf8f631d9a9f74a3aafba17)

2023-05-26 07:51 UTC, PavelMSTU approved these changes
Подозрительно не к чему придраться... :)

2023-05-26 07:51 UTC, merged