Создал metadata.md
kib-sources/stego-mp4-link pull request #2
Opened 2023-02-06 15:11 UTC by yourProgrammist

Тест выполнен

2023-02-13 21:54 UTC, nurovAm approved these changes

2023-02-14 08:07 UTC, PavelMSTU requested changes
Чукча не читатель, чукча писатель :))

**Дальнейшие действия:**
1) звонок на двоих и поправьте лексику. "коробка", "  Зарезервированная позиция" вместо просто "зарезервировано"... 
С любого языка нужно переводить, ПОНИМАЯ то что переводишь. 
2) после MR давайте делать на звонке с П.В.  

Много времени не тратьте. Как я понмаю вы пока ещё не можете эту работу сделать  хорошо. Это нормально. 

Давайте на п.1 -- 2 созвона по часу.

Пункт 2 -- один созвон на 40 минут.

2023-02-14 08:07 UTC, PavelMSTU commented on metadata.md
> +
Чем чанк отличается от контейнера? 
Определение чанка и контейнера

2023-02-14 08:07 UTC, PavelMSTU commented on metadata.md
> +| box type |  4 |          Тип коробки (mvhd) |
Что такое "коробка" ?

2023-07-21 08:35 UTC, PavelMSTU approved these changes

2023-07-21 08:36 UTC, merged