Создали вкрапление, извлечени и проверили работоспособность
kib-sources/stego-mp4-link pull request #7
Opened 2023-02-12 19:53 UTC by nurovAm

Задание выполнено

2023-02-13 17:43 UTC, PavelMSTU requested changes
Проревьюил. Жду исправлений замечаний

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +        if (i < 40 or i > 55) and (i < 272 or i > 279):
Непонятно, что значат эти magic цифры.

Хотя бы комментарии сделайте:
```python
 if (i < 40 or i > 55) and (i < 272 or i > 279):
     # 40 - это ....
     # 55 - ...
     # 272- ...
     # 279 - ....

```

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +            chunk_length_num = int.from_bytes(chunk_length, "big")
Добавьте защиту от некорректного формата,

```python
if len(chunk_length) <4:
      raise Exception("ERROR: некоректный формат!")
```

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +nibble2day_ret = {
Непонятно, почему поменялся тип?

В `nibble2day` у нас  `<str>:<int>`.
Здесь не `<int>:<str>`, а `<str>:<str>`

Далее, почему так нельзя сделать?:
```python
nibble2day_ret = {value:key for (key, value) in nibble2day.items()}
```

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +nibble2hour_ret = {
См. коммент для `nibble2day_ret`

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +nibble2minutes_ret = {
См. коммент для `nibble2day_ret`

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +nibble2seconds_ret = {
См. коммент для `nibble2day_ret`

2023-02-13 17:43 UTC, PavelMSTU commented on poc/README.md
> +>python3 poc_mp4_link.py --em https://clck.ru/ваши6символов /file path/file.m4a /new file path/newfile.m4a
Используются ёлочки для вставки:
```
https://clck.ru/<ваши6символов>
```

Зачем два ключа?: `/new file` 
может один ключ?: `/new_file`

И сделайте проще:
```bash
~$ python3 poc_mp4_link.py --em https://clck.ru/<ваши6символов> --in <path *.m4a> --out <path *.m4a>
```

И раз прогрузили примеры, то сразу с примером
```bash
~$ python3 poc_mp4_link.py --em https://clck.ru/hGrkv --in sample.m4a --out stego.m4a
```

2023-02-13 17:43 UTC, PavelMSTU commented on poc/README.md
> +Чтобы расшифровать данные, в командной строке набираем:
Чтобы ИЗВЛЕЧЬ данные, ...

2023-02-13 17:43 UTC, PavelMSTU commented on poc/README.md
> +https://clck.ru/abcdef
Пример ссылки не настоящий. 
Дайте настоящую.

Например пусть везьде в качестве примера будет `https://clck.ru/hGrkv`

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +        if 40 <= i <= 47:
Аналогично magic символы. ПРодублировать комменты

2023-02-13 17:43 UTC, PavelMSTU commented on poc/poc_m4a_links.py
> +import sys
Понятно что это POC, но хотя бы глобальный `__doc__` написать можно? 

Не помещает так же автор, права (LGPL) и т.д.

Смотри внизу шаблон:



```
"""
...

Create at 12.02.2023 00:00:00
~/poc/poc_m4a_links.py
"""

__author__ = 'pavelmstu'
__copyright__ = 'KIB, 2023'
__license__ = 'LGPL'
__credits__ = [
    'pavelmstu',
]
__version__ = "20230212"
__status__ = "Production"
```

Только вместо `pavelmstu` внесите свои учётки на GitHub.

2023-02-13 21:54 UTC, yourProgrammist approved these changes

2023-02-14 07:55 UTC, PavelMSTU approved these changes
Годно.

2023-02-14 07:55 UTC, PavelMSTU commented on poc/poc_mp4_link.py
> +...
Здесь вместо `...` описание нужно сделать. 

Что это за файл? 

Но у вас есть  `poc\README.md`, поэтому просто напишите
```
см. poc/README.md
```

2023-02-14 07:55 UTC, PavelMSTU commented on poc/poc_mp4_link.py
> +...
Поправил: https://github.com/kib-sources/stego-mp4-link/commit/1969f090bae92eb37227a7d3d7f7ff877b71be05

2023-02-14 07:56 UTC, merged